### ISSUE TITLE
Unexpected token ::

### ISSUE THREAD

**Issue by faustinoaq** [bcardiff/crolog#1]
Hi, @bcardiff Crystal is a good language, I'm trying to do something with prolog and crystal, and
your library seems good but I can't run it because:
I don't know why it's happening

```
Error in ./src/CrystalProlog.cr:7: while requiring "crolog"
require "crolog"
^
in ./libs/crolog/crolog.cr:1: while requiring "./crolog/**"
require "./crolog/**"
^
Syntax error in ./libs/crolog/crolog/atom.cr:5: unexpected token: ::
    @atom :: LibProlog::Atom
```

Can you tell me, what i can do to work well with this library?

Thanx!

**Comment by bcardiff** [comment]
Hi @faustinoaq, I just updated this _outdated_ experiment to bring prolog and crystal a little bit together. Now all samples and specs work with crystal 0.18. 

Thanks for the interest!
It's been a while since this was done, so I would probably do things a little bit different now. 
But enjoy either way :-)

**Comment by faustinoaq** [comment]
Oh, thank you very much! 🎉 
My Prolog code works well now 👍

**Comment by bcardiff** [comment]
Welcome! If there is something shareable, please send me a link I am curious.

**Comment by faustinoaq** [comment]
@bcardiff OK, is a college project, i will share when is complete. Something about shortest path of public transport in my town.
